### ISSUE TITLE
Mutiple deploys per 1 save

### ISSUE THREAD

**Issue by ao-omega** [msrivastav13/DX-Code-Companion#10]
All of a sudden, since last week, when hitting CTRL+S, the sfdx:deploy command will run multiple times.

**Comment by msrivastav13** [comment]
Thank you for reporting . I am going to fix this asap I can .

**Comment by ao-omega** [comment]
Thank you for building all of this!

**Comment by msrivastav13** [comment]
@ao-omega I just patched the issue .It will auto update in a while .Thank you

**Comment by ao-omega** [comment]
Tested, works like a charm.

Excellent job Mohith, congrats for such an awesome Extension!

Alberto Ojedo Marcos
Salesforce Technical Lead
+34911928801
aojedo@omegacrmconsulting.com
www.omegacrmconsulting.com
