### ISSUE TITLE
CCDX:Save to Salesforce or Ctrl + Shift + C don't work

### ISSUE THREAD

**Issue by ademarj** [msrivastav13/DX-Code-Companion#11]
This command show error message "command 'deploy.source' not found"
CCDX any command fails and shows respective error message.

Other example : CCDX Switch Org -> command 'switch.org' not found

mo-dx-plugin 0.2.0
Linux Mint 19.1 Cinnamon 64-bit
VSCode  version: 1.36.1 
salesforce-dx 46.6.0

Thank you very much

**Comment by msrivastav13** [comment]
Did you run `sfdx plugins:install mo-dx-plugin` to install the plugin . 

Have you installed the salesforce dx code companion vscode extension ?

**Comment by ademarj** [comment]
Yes !

Im linux terminal works fine, but in vscode extension don't work.

![image](https://user-images.githubusercontent.com/2036787/61976893-5d481780-afc3-11e9-961a-356e1bcf215b.png)

![image](https://user-images.githubusercontent.com/2036787/61976736-f1fe4580-afc2-11e9-9154-511388c9d793.png)

**Comment by msrivastav13** [comment]
Sorry I don't have specific Linux version to test this against .Do you want to send me email msrivastav13@gmail.com so that I debug with you. 

Thanks

**Comment by ademarj** [comment]
I already sent the e-mail.

Tks

**Comment by ademarj** [comment]
This issue was solved.
Thank you very much for your help.
