### ISSUE TITLE
Deploy apex throwing error

### ISSUE THREAD

**Issue by GeekyCopadoDeveloper** [msrivastav13/DX-Code-Companion#116]
Received below error on **Save to Salesforce** command.

PS C:\Users\Desktop\Office\Projects\Demo> sfdx deploy:apex -p "c:/Users/Akshay.Poddar/Desktop/Office/Projects/Demo/force-app/main/default/classes/HTTPCallout.cls"

 »   Warning: deploy:apex is not a sfdx command.
Did you mean help? [y/n]: y
 »   Error: Run sfdx help for a list of available commands.

**Comment by msrivastav13** [comment]
@GeekyCopadoDeveloper Did you run `sfdx plugins:install mo-dx-plugin`? It is required before you can get it working!

**Comment by GeekyCopadoDeveloper** [comment]
Yes, did all the pre-requisites. Throwing the attached error.
![image](https://user-images.githubusercontent.com/67841529/89163298-fd4f5e00-d592-11ea-8a32-ae6ff4d5b906.png)
