### ISSUE TITLE
Deploying apex class to sandbox not working.

### ISSUE THREAD

**Issue by anoopijt** [msrivastav13/DX-Code-Companion#130]
This is the message when trying to deploy, I am getting

$ sfdx deploy:apex -p "c:/Users/sesa431134/Documents/GitHub/IDMS/force-app/main
/default/classes/AP_IDMS_ConstantsUtility.cls"
 »   Warning: deploy:apex is not a sfdx command.
Did you mean help? [y/n]:
 »   Error: Run sfdx help for a list of available commands.

**Comment by anoopijt** [comment]
$ sfdx deploy:apex -p "c:/Users/sesa431134/Documents/GitHub/IDMS/force-app/main
/default/classes/AP_IDMS_ConstantsUtility.cls"
 »   Warning: deploy:apex is not a sfdx command.
Did you mean help? [y/n]:
 »   Error: Run sfdx help for a list of available commands.

**Comment by msrivastav13** [comment]
Did you run `sfdx plugins:install mo-dx-plugin` ?

**Comment by anoopijt** [comment]
It 

> Did you run `sfdx plugins:install mo-dx-plugin` ?

I was using the plugin from last one year. This week i have upgraded the salesforce cli to version 49. I think after only I was facing the issue. After running the install plugin, it was working again. 

Thank You!
