### ISSUE TITLE
Changing VS Code theme triggers a file save

### ISSUE THREAD

**Issue by guhaanandhnec08** [msrivastav13/DX-Code-Companion#14]
While any file is open (non-scratch org), I tried changing the color theme for VS-Code. It triggers a save and file gets saved in Salesforce.

**Comment by msrivastav13** [comment]
I am aware of this bug . Unfortunately I have not been able to find any workaround at this point for this. 

What I recommend is turn on the diff checker in the settings that would help to show a diff if it exists.

**Comment by guhaanandhnec08** [comment]
Sure. Thanks @msrivastav13

**Comment by msrivastav13** [comment]
@guhaanandhnec08 This is fixed now. Thanks for reporting this. Please update to latest 0.4.0. Thank you
