### ISSUE TITLE
Manage conflicts inaccuracies

### ISSUE THREAD

**Issue by eranvaizel** [msrivastav13/DX-Code-Companion#146]
Hi,

Great plugin, great job! I do have an issue though. It seems like every time I try to save a component I haven't recently dealt with, the plugin would detect my most recent change as a conflict with the server, although that's the only difference with the server, which is of course not the expected behavior. Only after refreshing from server, it seems to reset the history of the file and behave as expected. Is there anything I'm missing, a better way to resolve this issue?

Many thanks,
Eran

**Comment by msrivastav13** [comment]
@eranvaizel yes I am aware of this issue. Have not found a clean way to resolve it. A lot of times issue is also simply because of line breaks diff between metadata in org vs on your local.

I straight compare the body of the string. 

I will explore if I can fix it!

**Comment by eranvaizel** [comment]
Thing is, it doesn't indicate a change when there isn't one, so it's not about line breaks. It show as if my recent and only addition to the code is a conflict. So it seems more of a history accuracy issue rather than line breaks. As if the older version in Salesforce is the "correct" one, and my addition is a conflict. Could it be due to the current BETAness of force:source:diff ?

**Comment by msrivastav13** [comment]
@eranvaizel It does not use force:source: diff. It is a functionality that I have a custom built-in the vscode itself.

**Comment by eranvaizel** [comment]
@msrivastav13 I'm not entirely sure we're talking about the same thing, so I wonder if I might be using the tool in a wrong way. My issue is not about the tool indicating line breaks or empty lines as a change, that never happens. What does happen is the tool indicating conflict on changes that I've made to a file, and those are the **only** changes, both in reality and as indicated by the comparison screen. As if the tool doesn't "remember" the latest version of my own modification. Did you ever encounter into this issue?

**Comment by msrivastav13** [comment]
@eranvaizel I acknowledge the issue. I Will see if I can fix it once I get some free time. Appreciate the feedback.

**Comment by eranvaizel** [comment]
@msrivastav13 Many thanks. Our team at Facebook has a very relevant use case for your tool, let me know if there's anything we can do to help you explore and fix this issue.

**Comment by msrivastav13** [comment]
The project is open source! So feel free to submit PR  :)

I am going to see next week if I can find some time to see it I can detect this and fix it!

Thank you

**Comment by msrivastav13** [comment]
The Salesforce official extension does a far better job now for conflict detection. I recommend you to use that.

https://developer.salesforce.com/tools/vscode/en/user-guide/detect-conflicts

**Comment by cparmenter** [comment]
I tried it again and the official extension still does not do true conflict detection (like Developer Console does).  It detects all changes and presents them as conflicts - even if you made the previous change yourself.  Which is to say, it prompts every time you deploy, which is not useful.

**Comment by msrivastav13** [comment]
@CarlParmenterCLDPartners Please raise this issue on https://github.com/forcedotcom/salesforcedx-vscode/issues/new?template=Bug_report.md
