### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by prapul436** [msrivastav13/DX-Code-Companion#147]
- Issue Type: `Bug`
- Extension Name: `dx-code-companion`
- Extension Version: `0.4.7`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.49.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by msrivastav13** [comment]
@prapul436 whats the bug? Can you add more context and screenshot and description?
