### ISSUE TITLE
@msrivastav13 I found a nuance when deploying an unmanaged apex class (using CCDX): If it shares the same API name as a managed package apex class, CCDX attempts to save over the managed class instead of the unmanaged class. Same thing with visualforce pages and other components.

### ISSUE THREAD

**Issue by msrivastav13** [msrivastav13/DX-Code-Companion#16]
@msrivastav13 I found a nuance when deploying an unmanaged apex class (using CCDX): If it shares the same API name as a managed package apex class, CCDX attempts to save over the managed class instead of the unmanaged class. Same thing with visualforce pages and other components.

_Originally posted by @antnoley in https://github.com/msrivastav13/DX-Code-Companion/issues/2#issuecomment-562675077_

**Comment by msrivastav13** [comment]
@antnoley Could you please add steps to reproduce so I can fix it.May be some code sample so I can play with it .

**Comment by antnoley** [comment]
@msrivastav13 sure. Install a managed package (Salesforce CPQ is the one I installed) into a sandbox org. Find a VF Page within the managed package and take note of its name. Create a new unmanaged VF Page with the same name and commit to server. In VS Code, retrieve the unmanaged VF Page from server. In VS Code, make a change to the unmanaged VF Page. Using CCDX, run a comparison on the unmanaged VF Page. Note that the comparison compares it against the managed VF Page in the managed package.

**Comment by msrivastav13** [comment]
Thank you for the description. I am on vacation but once I am out , I will update you.

**Comment by msrivastav13** [comment]
@antnoley Sorry for delayed response. This is been fixed in the latest version. Please reopen if you still see issues.
