### ISSUE TITLE
ccProvider.js in /out should not be camelcased

### ISSUE THREAD

**Issue by StNick** [msrivastav13/DX-Code-Companion#17]
The case of this file causes the extension to fail on WSL installations (and presumably all Linux distros).  

Renaming it to ccprovider.js fixes the problem.

**Comment by nztradegroup** [comment]
@msrivastav13 I assume at some point you renamed ccProvider.ts to ccprovider.ts. If any build was run during while it was named the former, the output will be ccProvider.js, even after building with the renamed file.

The simple/safe solution for this is to make the build process clean the out directory before executing tsc.

**Comment by msrivastav13** [comment]
Thanks @nztradegroup ! I will look into it and hopefully fix it .Never tried on WSL

**Comment by msrivastav13** [comment]
Thank you @StNick @nztradegroup ! This is fixed with the latest version 0.4.0. Please let me know if you still see this.

I have deleted the out folder and regenerated it and seems to have fixed it.
