### ISSUE TITLE
Can i deploy folders using ccdx.

### ISSUE THREAD

**Issue by rajendrasnagar** [msrivastav13/DX-Code-Companion#198]
I don't see any option either via UI or CLI to push contents of a folder. CCDX saves files using tooling api which is much faster than OOB sfdx deploy command. However, I don't see the option to deploy the entire folder.
Is there any option available ?

**Comment by msrivastav13** [comment]
Are you not able to use `sfdx force:source:deploy -p <folder_path>` command from the terminal? This allows you to deploy by folder path.

Note if you are still using old metadata format then use `sfdx force:mdapi:deploy -d <folder path> --wait=-1 --json`

**Comment by rajendrasnagar** [comment]
Thanks Mohit. I always used to use this command for normal deployments. But  with complex, dependent class... Metadata api deployment is slow. And, this is the reason i switched to ccdx which uses tooling api. However, with this, I can deploy files not folder in single shot.

**Comment by msrivastav13** [comment]
I am going to be keep this open but note that it is lot of effort to run tooling deploy for files of different metadata!

I will see what options can be explored here!

Also note one thing there is a BETA feature from Salesforce in vscode extension pack for salesforce that uses tooling api.

You should try that and let me know!

This project is going to receive less attention compared to Salesforce official projects!

**Comment by rajendrasnagar** [comment]
Hi @msrivastav13 , are you talking about "Experimental: Deploy Retrieve". I will check this out.

Thanks for pointing this out.

**Comment by msrivastav13** [comment]
Yes that setting!
