### ISSUE TITLE
CCDX: Save To Salesforce is not showing errors

### ISSUE THREAD

**Issue by sfdcnoob** [msrivastav13/DX-Code-Companion#2]
**Version Information:**

```
Latitude-E7440:~/workspace/VSCODE_PROJECT$ sfdx plugins --core
@salesforce/plugin-generator 0.0.13 (core)
@salesforce/sfdx-trust 1.0.8 (core)
builtins 1.0.0 (core)
mo-dx-plugin 0.1.4
salesforcedx 45.0.9 (pre-release)

Latitude-E7440:~/workspace/VSCODE_PROJECT$ sfdx force --version
WARNING: apiVersion configuration overridden at 44.0

Latitude-E7440:~/workspace/VSCODE_PROJECT$ sfdx --version
sfdx-cli/6.42.0-ae478b3cb8 (linux-x64) node-v8.9.4

Latitude-E7440:~/workspace/VSCODE_PROJECT$ sfdx plugins
mo-dx-plugin 0.1.4
salesforcedx 45.0.9 (pre-release)
```

**Steps to Reproduce:**
- Create a trigger on Account object, referencing a field that doesn't exist in the org. For example:
```
trigger SimpleTrigger on Account (before insert) {    
    for(Account accObj : Trigger.New) {
        accObj.Give_Some_Invalid_Field_Name_Here__c == true;
    }
}

```
- Right click on the file and select the option `SFDX: Deploy This Source to Org` and this errors because field doesn't exist in Org.
- Right click on the file and select the option `CCDX: Save To Salesforce` and this doesn't output any error nor confirmation message saying saved successfully, here is the output:
```
Latitude-E7440:~/workspace/VSCODE_PROJECT$ sfdx deploy:trigger -p "/home/workspace/VSCODE_PROJECT/force-app/main/default/triggers/SimpleTrigger.trigger"
WARNING: apiVersion configuration overridden at 44.0
Saving ....... ⣯
```

Other information:
- I am working with Sandbox on Winter'19

Please let me know if you need any more details.

**Comment by msrivastav13** [comment]
@sfdcnoob I have fixed this issue . Get the latest plugin using the below

`sfdx plugins:uninstall mo-dx-plugin`

Once uninstalled install again using

`sfdx plugins:install mo-dx-plugin`

Running sfdx-plugin should say 0.1.5 version .

Let me know if this still does not fix  your issue .

And once again thank you

**Comment by sfdcnoob** [comment]
I just tested and it is fixed but I noticed something else:

If the trigger has two errors, before the fix, it used to show two errors but now, it is showing only one error.

**Comment by msrivastav13** [comment]
@sfdcnoob Does Salesforce SFDX command show you both of them ? The first failure is not a compile failure it's a data insert failure or a hard fail .The rest is compile failure ,so I am curious what sfdc shows .

**Comment by sfdcnoob** [comment]
@msrivastav13 It looks fine now. The CCDX and SFDX behavior is matching. Thanks for fixing it.

**Comment by antnoley** [comment]
@msrivastav13 I found a nuance when deploying an unmanaged apex class (using CCDX): If it shares the same API name as a managed package apex class, CCDX attempts to save over the managed class instead of the unmanaged class. Same thing with visualforce pages and other components.
