### ISSUE TITLE
sfdx deploy:apex command is failing and getting "ERROR running deploy:apex:  invalid cross reference id"

### ISSUE THREAD

**Issue by sesa431134** [msrivastav13/DX-Code-Companion#200]
On deploying the code getting the error " ERROR running deploy:apex:  invalid cross reference id".

System Information
Version: 1.53.2 (system setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by msrivastav13** [comment]
Can you let me the code you are deploying to make sure it’s not due to apex code itself failing to compile?
