### ISSUE TITLE
Is it possible to enable compile on Save?

### ISSUE THREAD

**Issue by sfdcnoob** [msrivastav13/DX-Code-Companion#3]
Right now, only when file really changes, the compilation is happening but consider the below scenario:

1. Created a Apex class referencing a non-existing field in the org and it shows error about field not existing.
2. I go into the org and create that new field and come back to the class and hit `ctrl+s` and compilation should happen. Can we have this?

It is not a big deal but coming from mavensmate, I found this as a gap.

As always, Thanks again for building this tool. I also just noticed that SFDX takes long time to compile class but this plug-in does quickly.

**Comment by msrivastav13** [comment]
@sfdcnoob I am not sure how mavensmate did this .I am going to keep this open .However note if you make any change like removing a colon and adding back , the ctrl+save should work .

The other is always the CCDX: Save To Salesforce command it will push .

Currently two features i really want to provide and is most priority is 

1. If server code has  changed , showing the diff between files .
2. Better deploy commands for the whole project. Something similar to changesets .
