### ISSUE TITLE
sObject type 'ContainerAsyncRequest' is not supported

### ISSUE THREAD

**Issue by rajendrasnagar** [msrivastav13/DX-Code-Companion#316]
Getting below error when trying to save the file.
![image](https://user-images.githubusercontent.com/3901703/140982874-abde6116-7796-4952-97c4-24346cc309fe.png)

Plugins Installed: 
![image](https://user-images.githubusercontent.com/3901703/140983032-39fb2f45-d6b3-48f5-a743-1cb39c7a90c6.png)

SFDX version:
![image](https://user-images.githubusercontent.com/3901703/140983122-b2705d2c-ef45-4ef8-b0f9-88e05a5cdd8f.png)

Previously, I was able to use the commands. But it seems with some update, if is getting failed now.

**Comment by msrivastav13** [comment]
@rajendrasnagar What permissions you have as this is working fine?

**Comment by rajendrasnagar** [comment]
I have a custom profile assigned to me. Other CCDX commands are working fine, only deploy command is throwing this error. Also, Normal SFDX deploy commands works file. It could be a specific permission issues, as I don't have full admin rights though.

**Comment by rajendrasnagar** [comment]
Seems to be permission issue.
