### ISSUE TITLE
dx-code-companion.autosave.enabled uses wrong deploy command

### ISSUE THREAD

**Issue by KoninosV2** [msrivastav13/DX-Code-Companion#45]
The dx-code-companion.autosave.enabled setting ,to deploy to salesforce automatically after every Save, uses the command 
sfdx deploy:apex -p "file/path"

The command for this function is now 
sfdx force:source:deploy -p "file/path"

**Comment by msrivastav13** [comment]
@KoninosV2 The sfdx deploy:apex is part of the custom plugin mo-dx-plugin I built. There is a difference between sfdx force:source:deploy and sfdx deploy:apex as the later uses tooling API and is much faster than the sfdx force:source:deploy.

Hope that makes sense.

**Comment by msrivastav13** [comment]
@KoninosV2 You can install the plugin using sfdx plugins:install mo-dx-plugin

**Comment by msrivastav13** [comment]
Also I recommend we switch off Salesforce auto save when this is enabled.

**Comment by msrivastav13** [comment]
You can now install the plugin as shown below now

![install_plugins](https://user-images.githubusercontent.com/2276156/74599090-8a851180-504a-11ea-90a7-67e41a10cf60.png)
