### ISSUE TITLE
ERROR running AuraDeploy

### ISSUE THREAD

**Issue by sdlopez** [msrivastav13/DX-Code-Companion#5]
I'm receiving an error whenever I try to save an aura component (cmp, js, css...). The extension was working fine for me last friday

D:\Users\sdlopez\Documents\VSCode\Project1>sfdx deploy:aura -p "d:/Users/sdlopez/Documents/VSCode/Project1/force-app/main/default/aura/Whl_Distribution_Process_Table/Whl_Distribution_Process_Table.cmp"
ERROR running AuraDeploy:  The flag value "d:/Users/sdlopez/Documents/VSCode/Project1/force-app/main/default/aura/Whl_Distribution_Process_Table/Whl_Distribution_Process_Table.cmp" is not in the correct format for "directory."

I already updated the mo-dx-plugin to version 0.1.7 as I saw in the "Error deploying CSS" issue thread.

Thank you for everything! Very useful extension :)

**Comment by sdlopez** [comment]
Doing some research, it seems to be a problem with de path. If I manually change absolute path to relative path, it works fine:

![image](https://user-images.githubusercontent.com/10205837/52949230-025b2600-337c-11e9-8f0b-138362e3c7bd.png)

**Comment by msrivastav13** [comment]
@sdlopez Thanks for reporting this issue .Which os version are you on ?

Is the problem happening for apex class files as well ?

Thanks

**Comment by sdlopez** [comment]
Hi @msrivastav13 , I'm using Windows 10.0.15063, and it's happening for apex classes as well

![image](https://user-images.githubusercontent.com/10205837/52956990-f29a0c80-3390-11e9-81ab-41a0fd3683c7.png)

Thank you!

**Comment by msrivastav13** [comment]
Again huge thank you for reporting since I don't test on Windows .I am going to boot my machine and revert the path variables across the code .

**Comment by msrivastav13** [comment]
@sdlopez I have pushed a new version for 0.1.8 with path using the previous strings .I am hoping that fixes .Please let me know how it goes .

You will have to update using sfdx plugins:update for this .

**Comment by sdlopez** [comment]
@msrivastav13 Is working perfecty again =)

![image](https://user-images.githubusercontent.com/10205837/52958374-435f3480-3394-11e9-9908-5c63326b7725.png)

Huge thank you!!
