### ISSUE TITLE
Cannot find module './providers/contentProvider'.

### ISSUE THREAD

**Issue by jprichter** [msrivastav13/DX-Code-Companion#6]
I cannot use the extension at all because of this error. I can use the plugin by itself when I put in the commands at the command line, but trying the same commands from the command pallette in VSCode fails everytime. 

I am using the latest version of VSCode and have uninstalled and reinstalled the extension and plugin several times.

When I toggle the Developer Tools, this is the error I see:

[Extension Host] Activating extension 'MohithShrivastava.dx-code-companion' failed: Cannot find module './providers/contentProvider'.

**Comment by msrivastav13** [comment]
@jprichter Thanks for reporting this .I do not experience this and hence I am going to try reproducing this.

What is your operating system ?And when did it stopped working?

**Comment by jprichter** [comment]
I'm using this inside Linux on Chrome OS. I don't remember exactly when it stopped working.

**Comment by jprichter** [comment]
This is what shows whenever I try to use any of the commands.
![image](https://user-images.githubusercontent.com/974193/54365675-ad8e9080-4645-11e9-9793-70734f94c034.png)

**Comment by msrivastav13** [comment]
I just made the contentProvider folder as ContentProvider and published a patch .Hoping this fixes it for chrome OX linux shell .

**Comment by msrivastav13** [comment]
@jprichter released an update to this and i am hoping since i changed the provider name it is no more an issue to you . Let me know if you still see issue .
