### ISSUE TITLE
Manage Conflicts with server is not working for apex Components and also not saving the local file to server.

### ISSUE THREAD

**Issue by anoopijt** [msrivastav13/DX-Code-Companion#7]
When we save the apex class, it's showing the difference from server and asking us to overwrite. This is not happening for apex components. Save is not working at all. 
Please refer the screen shot attached. It's just showing one notification Comparing with server copy.
![image](https://user-images.githubusercontent.com/19261111/54900509-8fece100-4ef9-11e9-8db0-3e52bb1ba99c.png)

**Comment by msrivastav13** [comment]
@anoopijt I have fixed this issue and released a patch .If you are on latest version you should be able to save it to server .

Also do you know you can switch off that manage conflict feature in the settings if you are only developer in the org .

Hope this helps .
