### ISSUE TITLE
deploy:vf is not recognized  

### ISSUE THREAD

**Issue by mh884** [msrivastav13/DX-Code-Companion#8]
sfdx deploy:vf -p "******************"
 »   Warning: deploy:vf is not a sfdx command.
Did you mean plugins? [y/n]:
 »   Error: Run sfdx help for a list of available commands.

**Comment by msrivastav13** [comment]
Hello .

Thanks for reporting .

The recent Salesforce cli update would have wiped mo-dx-plugin plugin .

Please run

sfdx plugins:install mo-dx-plugin

**Comment by msrivastav13** [comment]
@mh884  Did your issue resolved ? Can i closed this ?

**Comment by msrivastav13** [comment]
I am closing this since not much response from the author and i believe this is not an issue anymore .

**Comment by DigitalTheorist** [comment]
Had this same issue and your update fixed it for me. Thanks!
