### ISSUE TITLE
CCDX - Retrieve source from changeset not working

### ISSUE THREAD

**Issue by sun2say** [msrivastav13/DX-Code-Companion#9]
Hello - 

In order to bring the salesforce changes in the changeset from Sandbox to local project working directory, used the CCDX - Retrieve source from changeset not working command and provided the changeset Name and got the below error.

$ sfdx retrieve:pkgsource -n "SAL-740 - Creation of an automated Apex test infrastructure" -r changesets/sal-740-creationofanautomatedapextestinfra
structure/src
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

Need a help.

Thanks.
Sam

**Comment by msrivastav13** [comment]
@sun2say What is the version of mo-dx-plugin ? you can run `sfdx plugins` to tell you the version .
Please add as many details so i can help you resolve this quickly .
