### ISSUE TITLE
Cannot deserialize instance of complexvalue from VALUE_STRING value         3        177        npsp     or request may be missing a required field at [line:1, column:3455]

### ISSUE THREAD

**Issue by hwong103** [msrivastav13/DX-Code-Companion#93]
`Cannot deserialize instance of complexvalue from VALUE_STRING value         3        177        npsp     or request may be missing a required field at [line:1, column:3455]`

After a day of working with no issues the extension is having issues deploying to salesforce now. As far as I could tell it's due to the associated xml file. If I remove the package version from the xml file then it'll successfully deploy. 

Not sure what changed during the day but this hasn't been an issue until now

`<?xml version="1.0" encoding="UTF-8"?>
<ApexClass xmlns="http://soap.sforce.com/2006/04/metadata">
    <apiVersion>49.0</apiVersion>
    <packageVersions>
        <majorNumber>3</majorNumber>
        <minorNumber>177</minorNumber>
        <namespace>npsp</namespace>
    </packageVersions>
    <status>Active</status>
</ApexClass>
`

Extension Version: 0.4.0
Version: 1.45.1 (system setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by msrivastav13** [comment]
@hwong103 Thanks for reporting this. This might be a bug and i am going to close look at it. Note that i had to improve the apex compile for insert scenario and this might be a regression.

**Comment by msrivastav13** [comment]
@hwong103 This should be fixed now. Thanks for using the extension.

To get the fix type `sfdx plugins:update`

Please let me know if it still errors out.

**Comment by hwong103** [comment]
@msrivastav13 thanks so much for fixing this. We're back in business!

**Comment by msrivastav13** [comment]
Again i appreciate raising issue and using extension. Please show some love with stars on vscode marketplace.
