### ISSUE TITLE
Cannot install new extension version 0.4.4

### ISSUE THREAD

**Issue by danyin777** [msrivastav13/DX-Code-Companion#94]
Before trying to update to the new version, it was working fine, but when I tried to update, I got a failure message which tells me to Download Manually.
I unninstalled the extension and now I'm not able to install.
Trying to install from VSIX I get the following error "ENOENT: no such file or directory, mkdir".

I reinstalled the VSCode and the problem persists.

**Comment by msrivastav13** [comment]
@danyin777 Thanks for using the extension. Which operating system you are using ? I am making some more edits now and hoping that would fix it.

**Comment by danyin777** [comment]
Hello,

I'm using Windows 10 Pro.

Thanks!

**Comment by msrivastav13** [comment]
@danyin777 Not sure what has caused this issue only on windows. I just pushed a new update with really no change. It worked fine for me. Try to install again and let me know how it goes.

Again i appreciate raising issue and using extension. Please show some love with stars on vscode marketplace.

**Comment by danyin777** [comment]
@msrivastav13 I could install now without problem! Thank you very much. This extension is life!
