### ISSUE TITLE
[Feature Request] Show how much time it took for deploying into orgs

### ISSUE THREAD

**Issue by pranayjswl007** [msrivastav13/DX-Code-Companion#99]
One of the things I noticed is I cannot easily see how much time it took to actually save a file using DX code companion. Standard sfdx plugin shows time stamp, and Illuminate cloud shows seconds/mins consumed in deployment,

**Comment by msrivastav13** [comment]
@pranayjswl007 Thanks for raising this. Can you help me understand why you need these time -stamps? I can add it but want to make sure I know why we need this.

**Comment by msrivastav13** [comment]
Also, I still recommend the salesforce official plugin for larger deployment. While for incremental the DX Code Companion is a good choice until salesforce gets it right in their official plugin. There is work in progress on that and we should see huge improvements soon.

**Comment by msrivastav13** [comment]
@pranayjswl007 This is fixed. Update the extension and also run `sfdx plugins:update`. Shows how much time is taken for the command execution.
